### ISSUE TITLE
Add more flexibility for firestore emulator host.

### ISSUE THREAD

**Issue by ctschubel** [quarkiverse/quarkus-google-cloud-services#630]
I would like to use the firestore emulator for testing my quarkus application.
My issue is that the producer (to be precise the method 
 io.quarkiverse.googlecloudservices.firestore.runtime.FirestoreProducer.useEmulatorCredentials()) only allows me to use a firestore emulator if 'quarkus.google.cloud.firestore.host-override' contains 'localhost'. I use gitlab-ci to run my tests and my build pipeline is configured to publish the firestore service not as 'localhost' but 'firestore' (firestore:9000).
Something like:

```
...
services:
  - name: google/cloud-sdk
    alias: firestore
    pull_policy: always
    command:
    - gcloud
    - emulators
    - firestore
    - start
    - "--host-port=0.0.0.0:9000"
```

Its no big deal to overwrite that alias with localhost. It would just save me some configuration to allow other hosts as emulatorHosts as well. I use 'firestore' as standard alias for a while now and have some other apps written in SpringBoot that use the same ci configuration.
